### ISSUE TITLE
Create CI Build for C# Samples

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-csharp-samples#5]
This is a two-pronged effort. 
1. We do need a CI Build for these samples
2. We'd like to standardize how we do our builds across various projects and this serves as another data point for what works and what does not.

**Comment by bbgbear** [comment]
In you samples the ExpectedException attribute does not seem to function as expected. 
The following test will pass 
  [Test]
        [ExpectedException(typeof(FileLoadException))]
        public void HandlesArgumentExceptionAsType()
        {
            FileStream fs = File.Open(@"c:\foo.foo", FileMode.Open, FileAccess.Write);
        }

**Comment by CharliePoole** [comment]
This doesn't show up in the github issue for some reason - only in my email.

I created a new issue nunit/nunit-csharp-samples#7 to cover this. Adding
unrelated problems to an existing issue doesn't allow us to track it as we
need to.

**Comment by bbgbear** [comment]
Hey
I deleted. The problem was due to compatibility issues with Jet Brains
resharper. I now have it working using the nuint console.

Please mark as complete, or delete, or close. Or all of the above.

Steve

**Comment by CharliePoole** [comment]
OK, I closed the issue. Thanks!

**Comment by CharliePoole** [comment]
Closed by PR #6
