### ISSUE TITLE
Should samples work in VS 2015 Community Edition?

### ISSUE THREAD

**Issue by MikeTheGreat** [nunit/nunit-csharp-samples#8]
Hello!

I downloaded this repo as a .ZIP, extracted it, and then opened up the nunit-csharp-samples-master\syntax\cs-syntax.sln file in Visual Studio 2015 Community Edition.  It built just fine (no compile time errors), but when I brought up the Test Explorer & clicked on "Run All" the Test Explorer window remains blank/empty.

Same thing with the 'Money' demo.

Are these supposed to work 'out of the box' like this, or am I missing something?
(I'm guessing that I'm missing something, but I'd appreciate any advice / pointers / links that could help set me straight).

In case it's helpful, here's my VS info:
```
Microsoft Visual Studio Community 2015
Version 14.0.25123.00 Update 2
Microsoft .NET Framework
Version 4.6.01055

Installed Version: Community

Visual Basic 2015   00322-20000-00000-AA441
Microsoft Visual Basic 2015

Visual C# 2015   00322-20000-00000-AA441
Microsoft Visual C# 2015

Visual C++ 2015   00322-20000-00000-AA441
Microsoft Visual C++ 2015

Application Insights Tools for Visual Studio Package   5.209.60613.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2015 (RC1 Update 1)   14.1.20203.0
ASP.NET and Web Tools 2015 (RC1 Update 1)

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.40314.0
For additional information, visit http://www.asp.net/

Azure App Service Tools v2.7.1   14.0.11112.0
Azure App Service Tools v2.7.1

Common Azure Tools   1.7
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

GitHub.VisualStudio   1.0
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

NuGet Package Manager   3.4.4
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

Python Tools for Visual Studio   2.2.40315.00
Python Tools for Visual Studio provides IntelliSense, projects, templates, Interactive windows, and other support for Python developers.

Python Tools for Visual Studio - Django Integration   2.2.40315.00
Provides templates and integration for the Django web framework.

Python Tools for Visual Studio - Profiling Support   2.2.40315.00
Profiling support for Python projects.

SQL Server Data Tools   14.0.60311.1
Microsoft SQL Server Data Tools

TypeScript   1.8.29.0
TypeScript tools for Visual Studio
```

**Comment by CharliePoole** [comment]
It looks as if you haven't installed NUnit in any form. Since you are using test explorer, you will probably want the NUnit 3 Visual Studio Adapter.

**Comment by rprouse** [comment]
The samples are code only, they don't ship with runners or adapters. In Visual Studio, go to **Tools | Extensions and Updates** and install the NUnit 3 Visual Studio Adapter as @CharliePoole mentioned.

**Comment by MikeTheGreat** [comment]
Aha!  This is perfect!  Thank you very much, @CharliePoole  and @rprouse!

If you don't mind, I've got a question:

I tried using NuGet so that I could install the adapter into the solution (as opposed to using Tools | Extensions and Updates, which installs the adapter into this particular installation of Visual Studio, on this particular computer).  I tried installing something which said that it was an NUnit Visual Studio adapter package but it didn't work (Test Explorer couldn't see the NUnit tests).

I kept adding NuGet packages, and by the end I think I had added pretty much every NuGet package that said 'NUnit' into my solution.  It still wasn't working :)

Clearly I'm misunderstanding something about NuGet/NUnit - is there a tutorial somewhere that explains how to use NuGet & NUnit together?

**Comment by CharliePoole** [comment]
You nave to install the NUnit 3 Visual Studio Adapter,  which is not the same as the NUnit Visual Studio Adapter. I know! What were we  thinking? You should not need any other nunit packages as the sample project already includes the nunit framework. However, if you need to upgrade or replace it, that package is simply called "NUnit".

**Comment by MikeTheGreat** [comment]
Cool, thanks!

Hey, while I've got you two - 
In an earlier version of NUnit (2.5?) there was a way to run the tests and produce the results in XML.  I think it was an option on the console runner.  

It was nice because I could write a C# program that ran the NUnit tests to get the XML, then used XSLT to produce an HTML report of the tests.

If you don't mind my asking - how does one do that now?  Which Extension should I install into Visual Studio?  (Is there a tutorial/how-to for using the NUnit-console-runner in a C# program?)

Thank you both for your time and knowledge - I'm trying to upgrade an older suite of NUnit tests and this is extremely helpful!!!
